program: src/vae/train.py
name: sweepdemo
project: vae_sparrow
entity: jhz209-university-of-copenhagen
method: bayes
metric:
    goal: minimize
    name: validation_loss
parameters:
    hyperparameters.batch_size:
        values: [16, 32, 64]
    hyperparameters.n_epochs:
        values: [10, 15, 20]
    hyperparameters.lr:
        min: 0.00001
        max: 0.001
        distribution: log_uniform_values
run_cap: 10
